import dashboardMockup from './dashboard-mockup.webp';
import notFoundIllustration from './404-illustration.png';
import errorIllustration from './error-illustration.png';
import comingSoonIllustration from './coming-soon-illustration.png';
import warehouse from './warehouse.png';
import deliveryPackageIcon from './delivery-package-icon.png';
import deliveryPackageIconDelivered from './delivery-package-icon-delivered.png';
import deliveryPackageIconPending from './delivery-package-icon-pending.png';
import paymentConfirmation from './payment-confrimation.png';
import truck from './truck.png';
import mapPin from './map-pin.png';
import truckBw from './truck-bw.png';
import locateMe from './locate-me.png';
import generateStatementIcon from './generate-statement-icon.png';
import markerIcon2x from './marker-icon-2x.png';
import markerIcon from './marker-icon.png';
import markerShadow from './marker-shadow.png';
import MoneyBox from './moneyBox.png';
import BoxOpen from './boxopened.png';
import SuccessBox from './box-success.png';
export { BoxOpen as BoxOpenIcon };
export { SuccessBox };
export { MoneyBox as MoneyBoxIcon };
export { dashboardMockup as DashboardMockup };
export { notFoundIllustration as NotFoundIllustration };
export { errorIllustration as ErrorIllustration };
export { comingSoonIllustration as ComingSoonIllustration };
export { warehouse as WarehouseIcon };
export { deliveryPackageIcon as DeliveryPackageIcon };
export { deliveryPackageIconDelivered as DeliveryPackageIconDelivered };
export { deliveryPackageIconPending as DeliveryPackageIconPending };
export { paymentConfirmation as PaymentConfirmationImage };
export { truck as TruckIcon };
export { mapPin as MapPinIcon };
export { truckBw as TruckBwIcon };
export { locateMe as LocateMeIcon };
export { generateStatementIcon as GenerateStatementIcon };
export { markerIcon2x as MarkerIcon2x };
export { markerIcon as MarkerIcon };
export { markerShadow as MarkerShadow };
