import type { PaymentInvoiceMock } from './paymentInvoiceTypes';

/** Default invoice modal payload (Figma B2B-clients). Spread into pickup confirmation / invoice UI with booking-specific fields. */
export const MOCK_PAYMENT_INVOICE: PaymentInvoiceMock = {
  invoiceId: '#INV-1051',
  billToName: 'UrbanNest Home',
  billToEmail: 'accounts@urbannesthome.co.uk',
  billToAddress: '55 Bridge End, Cardiff, CF10 2BN, UK',
  issuedOn: 'December 07, 2026',
  dueDate: 'December 27, 2026',
  paymentMethodLabel: 'Card Payment',
  cardholderName: 'John Doe',
  cardNumber: '**** **** **** 4532',
  paymentDate: 'December 21, 2026',
  paidAmount: '£360.96',
  bookingOrderId: 'SWC-BK-01234',
  totalStops: '03',
  totalPackages: '14',
  totalWeight: '57 kg',
  serviceType: 'Mixed (Fastest, Standard)',
  stops: [
    {
      stop: '01',
      trackingId: 'SWC-BK-01234',
      customer: 'Black Marvin',
      postcode: 'B6A 5TR',
      tier: 'FASTEST',
      packages: '4',
      weight: '18 kg',
      total: '£81.60',
    },
    {
      stop: '02',
      trackingId: 'SWC-BK-01234',
      customer: 'Brooklyn Simmons',
      postcode: 'B2T 9MS',
      tier: 'STANDARD',
      packages: '2',
      weight: '19 kg',
      total: '£44.16',
    },
    {
      stop: '03',
      trackingId: 'SWC-BK-01234',
      customer: 'Jenny Wilson',
      postcode: 'B3T 9SB',
      tier: 'ECONOMY',
      packages: '6',
      weight: '27 kg',
      total: '£144.36',
    },
    {
      stop: '04',
      trackingId: 'SWC-BK-01234',
      customer: 'Ronald Richards',
      postcode: 'B3J 9TR',
      tier: 'STANDARD',
      packages: '5',
      weight: '29 kg',
      total: '£70.44',
    },
  ],
  subtotal: '£340.56',
  vat: '£20.40',
  total: '£360.96',
  companyEmail: 'shiftopus@gmail.com',
  companyPhone: '+44 7700 900123',
  companyAddress: '55 Bridge End, Cardiff, CF10 2BN, UK',
  chargesNoteTitle: 'How Shipment Charges Are Calculated',
  chargesNoteBody:
    'Shipment cost is based on Chargeable Weight × Rate per kg. Chargeable Weight = greater of Actual Weight and Volumetric Weight. Volumetric Weight Formula: (Length × Width × Height) ÷ 5000',
};
