import swCouriersLogo from './SWCouriersLogo.svg';
import whiteLogo from './white-logo.svg';
import deleteSavedViewIllustration from './delete_saved_view.svg';
import noChangesRecordIllustration from './no_changes_record.svg';
import noCreditAccountIllustration from './no_credit_account.svg';
import noInvoicesYetIllustration from './no_invoices_yet.svg';
import noPaymentHistoryIllustration from './no_payment_history.svg';
import viewLabelsIcon from './ViewLabels.svg';
import LoadingSpinner from './LoadingSpinner';
import TruckRunning from './TruckRunning';
import StartLocation from './StartLocation';
import DestinationLocation from './DestinationLocation';
import financialSummaryIllustration from './financial_summary.svg';
import deleteDraftBookingIllustration from './deleteDraftBooking.svg';
import deleteDraftApplicationIllustration from './deleteDraftApplication.svg';
import noDraftApplicationsIllustration from './noDraftApplications.svg';
import creditApplicationWalletIllustration from './creditApplicationWallet.svg';
import creditApplicationHeaderIllustration from './creditApplicationHeader.svg';
import addNoteIllustration from './addNote.svg';
import editNoteIllustration from './editNote.svg';
import deleteNoteIllustration from './deleteNote.svg';
import noNotesIllustration from './noNotes.svg';
import cancelIllustration from './cancel.svg';
import editDeliveryPreferencesIllustration from './editDeliveryPreferences.svg';
import signatureIllustration from './signature.svg';
import leaveSafePlaceIllustration from './leaveSafePlace.svg';
import attachmentsIllustration from './attachments.svg';
import invoiceOverdue from './icons/billing/invoice-overdue.svg';
import invoiceTotalInvoices from './icons/billing/invoice-total-invoices.svg';
import invoiceTotalPaid from './icons/billing/invoice-total-paid.svg';
import invoiceTotalUnpaid from './icons/billing/invoice-total-unpaid.svg';
import paymentAllocated from './icons/billing/payment-allocated.svg';
import paymentPending from './icons/billing/payment-pending.svg';
import paymentTotalPayments from './icons/billing/payment-total-payments.svg';
import paymentUnallocated from './icons/billing/payment-unallocated.svg';
import refundTotalAmount from './icons/billing/refund-total-amount.svg';

export { swCouriersLogo as SwCouriersLogo };
export { financialSummaryIllustration as FinancialSummaryIllustration };
export { whiteLogo as WhiteLogo };
export { deleteSavedViewIllustration as DeleteSavedViewIllustration };
export { noChangesRecordIllustration as NoChangesRecordIllustration };
export { noCreditAccountIllustration as NoCreditAccountIllustration };
export { noInvoicesYetIllustration as NoInvoicesYetIllustration };
export { noPaymentHistoryIllustration as NoPaymentHistoryIllustration };
export { viewLabelsIcon as ViewLabelsIcon };
export { LoadingSpinner };
export { TruckRunning };
export { StartLocation };
export { DestinationLocation };
export { deleteDraftBookingIllustration as DeleteDraftBookingIcon };
export { deleteDraftApplicationIllustration as DeleteDraftApplicationIcon };
export { noDraftApplicationsIllustration as NoDraftApplicationsIcon };
export { creditApplicationWalletIllustration as CreditApplicationWalletIcon };
export { creditApplicationHeaderIllustration as CreditApplicationHeaderIcon };
export { addNoteIllustration as AddNoteIllustration };
export { editNoteIllustration as EditNoteIllustration };
export { deleteNoteIllustration as DeleteNoteIllustration };
export { noNotesIllustration as NoNotesIllustration };
export { cancelIllustration as CancelIcon };
export { editDeliveryPreferencesIllustration as EditDeliveryPreferencesIllustration };
export { signatureIllustration as SignatureIllustration };
export { leaveSafePlaceIllustration as LeaveSafePlaceIllustration };
export { attachmentsIllustration as AttachmentsIllustration };
export { invoiceOverdue as BillingInvoiceOverdueIcon };
export { invoiceTotalInvoices as BillingInvoiceTotalInvoicesIcon };
export { invoiceTotalPaid as BillingInvoiceTotalPaidIcon };
export { invoiceTotalUnpaid as BillingInvoiceTotalUnpaidIcon };
export { paymentAllocated as BillingPaymentAllocatedIcon };
export { paymentPending as BillingPaymentPendingIcon };
export { paymentTotalPayments as BillingPaymentTotalPaymentsIcon };
export { paymentUnallocated as BillingPaymentUnallocatedIcon };
export { refundTotalAmount as BillingRefundTotalAmountIcon };
