/**
 * Braintree React Context
 *
 * Fetches and provides the Braintree client token required for Drop-in UI.
 * Client token must be generated by your backend using Braintree server SDK.
 * @see https://developer.paypal.com/braintree/docs/start/drop-in/
 * @see https://developer.paypal.com/braintree/docs/start/hello-client/
 */

import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';
import { env } from '@/config/env';

interface BraintreeContextValue {
  /** Braintree client token for Drop-in authorization */
  clientToken: string | null;
  /** True while fetching the client token */
  isLoading: boolean;
  /** Error from client token request */
  error: Error | null;
  /** Re-fetch client token (e.g. after token expiry) */
  refetch: () => Promise<void>;
}

const BraintreeContext = createContext<BraintreeContextValue | null>(null);

function getClientTokenUrl(): string {
  const url = env.VITE_BRAINTREE_CLIENT_TOKEN_URL;
  if (url) return url;
  const base = env.VITE_API_BASE_URL;
  return base.endsWith('/') ? `${base}braintree/client-token` : `${base}/braintree/client-token`;
}

async function fetchClientToken(): Promise<string> {
  const url = getClientTokenUrl();
  const response = await fetch(url, {
    method: 'GET',
    headers: { Accept: 'application/json' },
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(
      `Braintree client token request failed (${response.status}): ${text || response.statusText}`
    );
  }

  const data = (await response.json()) as { clientToken?: string; token?: string } | string;
  const token =
    typeof data === 'string'
      ? data
      : ((data as { clientToken?: string; token?: string }).clientToken ??
        (data as { clientToken?: string; token?: string }).token);
  if (typeof token !== 'string' || !token.trim()) {
    throw new Error('Invalid client token response: missing or empty token');
  }
  return token.trim();
}

interface BraintreeProviderProps {
  children: React.ReactNode;
  /** If true, token is fetched only when consumer needs it (lazy). Default false = fetch when provider mounts. */
  lazy?: boolean;
}

export function BraintreeProvider({
  children,
  lazy = false,
}: BraintreeProviderProps): React.JSX.Element {
  const [clientToken, setClientToken] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(!lazy);
  const [error, setError] = useState<Error | null>(null);

  const loadToken = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const token = await fetchClientToken();
      setClientToken(token);
    } catch (err) {
      setError(err instanceof Error ? err : new Error(String(err)));
      setClientToken(null);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!lazy) void loadToken();
  }, [lazy, loadToken]);

  const value: BraintreeContextValue = {
    clientToken,
    isLoading,
    error,
    refetch: loadToken,
  };

  return <BraintreeContext.Provider value={value}>{children}</BraintreeContext.Provider>;
}

export function useBraintree(): BraintreeContextValue {
  const ctx = useContext(BraintreeContext);
  if (ctx == null) {
    throw new Error('useBraintree must be used within a BraintreeProvider');
  }
  return ctx;
}

export function useBraintreeOptional(): BraintreeContextValue | null {
  return useContext(BraintreeContext);
}
